apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: zk0
    ceshi: ceshi
    name: label-component-zk-cluster-tjsw-0
  name: zk-cluster-tjsw-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk0
      ceshi: ceshi
      name: label-component-zk-cluster-tjsw-0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zk0
        ceshi: ceshi
        name: label-component-zk-cluster-tjsw-0
    spec:
      containers:
      - env:
        - name: ZOO_MY_ID
          value: "0"
        - name: ZOO_SERVERS
          value: server.0=0.0.0.0:2888:3888 server.1=zk-cluster-1:2888:3888 server.2=zk-cluster-2:2888:3888
        - name: ZOO_DATA_DIR
          value: /data/zk-data
        - name: ZOO_DATA_LOG_DIR
          value: /data/zk-logs
        - name: ZOO_TICK_TIME
          value: "1000"
        - name: ZOO_SYNC_LIMIT
          value: "2"
        image: abcsys.cn:5000/appstore-zookeeper:3.4.10
        imagePullPolicy: IfNotPresent
        name: zk-cluster-com-0
        ports:
        - containerPort: 2181
          protocol: TCP
        - containerPort: 2888
          protocol: TCP
        - containerPort: 3888
          protocol: TCP
        resources:
          limits:
            cpu: 800m
            memory: 2Gi
          requests:
            cpu: 400m
            memory: 512Mi
        volumeMounts:
        - mountPath: /data/zk-data
          name: zk-data
        - mountPath: /data/zk-logs
          name: zk-logs
      dnsPolicy: ClusterFirst
      hostname: zk-cluster-0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: zk-data
      - emptyDir: {}
        name: zk-logs

