apiVersion: v1
kind: Service
metadata:
  labels:
    service-name: kibana
  name: kibana
spec:
  clusterIP: 
  externalTrafficPolicy: Cluster
  ports:
  - name: kibana
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    application-real-name: kibana-20180428133944447
    image-group-name: kibana
    version-id: kibana
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    image-group-name: kibana
    version-id: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      image-group-name: kibana
  template:
    metadata:
      labels:
        application-real-name: kibana-20180428133944447
        image-group-name: kibana
        version-id: kibana
    spec:
      containers:
      - name: kibana
        image: registry.example.com:5000/kibana:5.6.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
          name: kibana-port
          protocol: TCP
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /
            port: 5601
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /
            port: 5601
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 800m
            memory: 512Mi
          requests:
            cpu: 400m
            memory: 256Mi
      dnsPolicy: ClusterFirst


