
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: nginx-app
spec:
  serviceName: "nginx-app"
  replicas: 2
  volumeClaimTemplates:
  - metadata:
      name: html
      annotations:
        volume.beta.kubernetes.io/storage-class: "ceph-rbd"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app
          image: nginx
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: html
              mountPath: "/usr/share/nginx/html/"

