kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: example-nfs
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: example.com/nfs
