apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: .NET Core Builder Images
    openshift.io/image.dockerRepositoryCheck: 2018-06-29T15:34:13Z
  creationTimestamp: null
  generation: 2
  name: dotnet
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: |-
        Build and run .NET Core applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/redhat-developer/s2i-dotnetcore/tree/master/2.0/build/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of .NET Core available on OpenShift, including major versions updates.
      iconClass: icon-dotnet
      openshift.io/display-name: .NET Core (Latest)
      sampleContextDir: app
      sampleRef: dotnetcore-2.0
      sampleRepo: https://github.com/redhat-developer/s2i-dotnetcore-ex.git
      supports: dotnet
      tags: builder,.net,dotnet,dotnetcore
    from:
      kind: ImageStreamTag
      name: "2.0"
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
