apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Apache HTTP Server (httpd)
    openshift.io/image.dockerRepositoryCheck: 2018-06-29T15:34:13Z
  creationTimestamp: null
  generation: 2
  name: httpd
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: |-
        Build and serve static content via Apache HTTP Server (httpd) on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/httpd-container/blob/master/2.4/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of Httpd available on OpenShift, including major versions updates.
      iconClass: icon-apache
      openshift.io/display-name: Apache HTTP Server (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/httpd-ex.git
      supports: httpd
      tags: builder,httpd
    from:
      kind: ImageStreamTag
      name: "2.4"
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
