apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Red Hat JBoss Data Virtualization 6.5 JDBC Driver Modules
      for EAP
    openshift.io/image.dockerRepositoryCheck: 2018-06-29T15:34:23Z
    openshift.io/provider-display-name: Red Hat, Inc.
    version: 1.4.7
  creationTimestamp: null
  generation: 2
  name: jboss-datavirt63-driver-openshift
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
