apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Red Hat JBoss EAP 7.1
    openshift.io/image.dockerRepositoryCheck: 2018-06-29T15:34:23Z
    openshift.io/provider-display-name: Red Hat, Inc.
    version: 1.4.7
  creationTimestamp: null
  generation: 2
  name: jboss-eap71-openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: JBoss EAP 7.1 Tech Preview.
      iconClass: icon-eap
      openshift.io/display-name: Red Hat JBoss EAP 7.1 (Tech Preview)
      sampleContextDir: kitchensink
      sampleRef: 7.0.0.GA
      sampleRepo: https://github.com/jboss-developer/jboss-eap-quickstarts.git
      supports: eap:7.1,javaee:7,java:8,xpass:1.0
      tags: builder,eap,javaee,java,jboss,hidden
      version: TP
    from:
      kind: ImageStreamTag
      name: 1.0-TP
    generation: 1
    importPolicy: {}
    name: TP
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
