apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Red Hat JBoss Web Server 3.0 Apache Tomcat 7
    openshift.io/image.dockerRepositoryCheck: 2018-06-29T15:34:23Z
    openshift.io/provider-display-name: Red Hat, Inc.
    version: 1.4.7
  creationTimestamp: null
  generation: 2
  name: jboss-webserver30-tomcat7-openshift
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
