apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Red Hat JBoss A-MQ 6.3
    openshift.io/image.dockerRepositoryCheck: 2018-06-29T15:34:23Z
    openshift.io/provider-display-name: Red Hat, Inc.
    version: 1.4.7
  creationTimestamp: null
  generation: 2
  name: jboss-amq-63
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
