apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: MariaDB
    openshift.io/image.dockerRepositoryCheck: 2018-06-29T15:34:13Z
  creationTimestamp: null
  generation: 2
  name: mariadb
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: |-
        Provides a MariaDB database on RHEL 7. For more information about using this database image, including OpenShift considerations, see https://github.com/sclorg/mariadb-container/tree/master/10.1/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of MariaDB available on OpenShift, including major versions updates.
      iconClass: icon-mariadb
      openshift.io/display-name: MariaDB (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      tags: mariadb
    from:
      kind: ImageStreamTag
      name: "10.1"
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
