apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Python
    openshift.io/image.dockerRepositoryCheck: 2018-06-29T15:34:13Z
  creationTimestamp: null
  generation: 2
  name: python
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: |-
        Build and run Python applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/3.5/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of Python available on OpenShift, including major versions updates.
      iconClass: icon-python
      openshift.io/display-name: Python (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/django-ex.git
      supports: python
      tags: builder,python
    from:
      kind: ImageStreamTag
      name: "3.5"
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
