apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Perl
    openshift.io/image.dockerRepositoryCheck: 2018-06-29T15:34:13Z
  creationTimestamp: null
  generation: 2
  name: perl
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: |-
        Build and run Perl applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-perl-container/blob/master/5.20/README.md.

        WARNING: By selecting this tag, your application will automatically update to use the latest version of Perl available on OpenShift, including major versions updates.
      iconClass: icon-perl
      openshift.io/display-name: Perl (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/openshift/dancer-ex.git
      supports: perl
      tags: builder,perl
    from:
      kind: ImageStreamTag
      name: "5.24"
    generation: 1
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
