apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Red Hat OpenJDK 8
    openshift.io/image.dockerRepositoryCheck: 2018-06-29T15:34:24Z
    openshift.io/provider-display-name: Red Hat, Inc.
    version: 1.4.7
  creationTimestamp: null
  generation: 2
  name: redhat-openjdk18-openshift
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
