kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rbd
provisioner: ceph.com/rbd
parameters:
  monitors: 192.168.1.8:6789
  pool: kube
  adminId: admin
  adminSecretNamespace: default
  adminSecretName: ceph-admin-secret
#  userId: kube
  userId: admin
  userSecretName: ceph-admin-secret
  imageFormat: "2"
  imageFeatures: layering

