apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-pv     
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  cephfs:              
    monitors:       
      - 66.1.43.81:6789
      - 66.1.43.82:6789
      - 66.1.43.83:6789
    path: /
    user: admin
    secretRef:
      name: ceph-secret 
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
