apiVersion: v1
kind: ReplicationController
metadata:
  name: rhel-ceph
  namespace: default
  labels:
    app: rhel-ceph
spec:
  replicas: 2
  selector:
    app: rhel-ceph
  template:
    metadata:
      name: rhel-ceph
      labels:
        app: rhel-ceph
    spec:
      containers:
      - image: registry.example.com:5000/rhel7.2:1124-3
        name: rhel-ceph
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
          name: app-port
          protocol: TCP
        volumeMounts:
        - mountPath: /mnt
          name: ceph
      volumes:
        - name: ceph
          persistentVolumeClaim:
            claimName: ceph-claim

