apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: source-ip-app
    name: nodeport
  spec:
    clusterIP: 
    ports:
    - nodePort: 31914
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      run: source-ip-app
    sessionAffinity: None
    type: NodePort
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: source-ip-app
    name: clusterip
  spec:
    clusterIP: 
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      run: source-ip-app
    sessionAffinity: None
    type: ClusterIP
