apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-pvrbd
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  rbd:              
    monitors:       
      - 66.1.43.81:6789
#      - 66.1.43.81:6789,66.1.43.82:6789,66.1.43.83:6789
    pool: rbd
    image: rbdim
    user: admin
    secretRef:
      name: ceph-secret 
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
