apiVersion: v1
kind: ReplicationController
metadata:
  name: rhel-cephrbd
  namespace: default
  labels:
    app: rhel-cephrbd
spec:
  replicas: 1
  selector:
    app: rhel-cephrbd
  template:
    metadata:
      name: rhel-cephrbd
      labels:
        app: rhel-cephrbd
    spec:
      containers:
      - image: registry.example.com:5000/rhel7.2:1124-3
        name: rhel-cephrbd
        ports:
        - containerPort: 8080
          name: app-port
          protocol: TCP
#        securityContext:
#          privileged: false
        volumeMounts:
        - mountPath: /mnt
          name: cephrbd
      volumes:
        - name: cephrbd
          persistentVolumeClaim:
            claimName: ceph-claimrbd

