# Default values for storageclass-ceph-rbd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: provisioner
rbac: rbd-provisioner

lables:
  company:
    key: company
    value: BoCloud
  department: 
    key: department
    value: services
  group: 
    key: group
    value: poc-and-testing
  environment: 
    key: environment 
    value: dev-and-testing


replicaCount: 1
image:
  repository: registry.cn-hangzhou.aliyuncs.com/jhr-k8s/rbd-provisioner
  tag: v0.1.1
  pullPolicy: IfNotPresent

secret:
  admin:
    name: ceph-admin-secret
    secretkey: QVFBczNoQmJYdXYvR3hBQXFSbG9LaDhEMkRiVVRMeGRhNUV2TFE9PQ==
  ceph:
    name: ceph-secret
    secretkey: QVFBQjZoQmJXMW82SkJBQUMzbG9CUnhvbUY2MVJ4V2pKSXR6eXc9PQ==

storageclass:
  name: ceph-rbd
  id:
    admin: admin  
    user: k8s
  pool: rbd
  monitors: "192.168.1.114:6789"
  provisioner: "ceph.com/rbd"
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  isdefault: true
  systemservices: true

resources: 
  limits:
   cpu: 1
   memory: 1024Mi
  requests:
   cpu: 500m
   memory: 512Mi
