apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: maven 3.5  jdk 8 Apache Tomcat 8
    openshift.io/provider-display-name: Red Hat, Inc.
    version: 1.4.7
  name: tomcat8-jdk8-maven-s2i
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: maven 3.5  jdk 8 Apache Tomcat 8 S2I images.
      iconClass: icon-rh-tomcat
      openshift.io/display-name: maven 3.5  jdk 8 Apache Tomcat 8
      tags: builder,tomcat,tomcat8,java,jboss,hidden
      version: "8.5-jdk8-mvn3.5.0"
    from:
      kind: DockerImage
      name: registry.example.com:5000/s2i-tomcat:8.5-jdk8-mvn3.5.0
    generation: 2
    importPolicy: 
      insecure: true
    name: "1.0"
    referencePolicy:
      type: Source

