apiVersion: v1
data:
  secret: {{ .Values.secret.admin.secretkey }}
kind: Secret
metadata:
  name: {{ .Values.secret.admin.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
---
apiVersion: v1
data:
  secret: {{ .Values.secret.ceph.secretkey }}
kind: Secret
metadata:
  name: {{ .Values.secret.ceph.name }}
type: Opaque
