apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.name }}
  {{- if .Values.storageclass.isdefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{ end }}
  {{- if .Values.storageclass.systemservices }}
  labels:
    kubernetes.io/cluster-service: "true"
  {{ end }}
parameters:
  adminId: {{ .Values.storageclass.id.admin }}
  adminSecretName: {{ .Values.secret.admin.name }}
  adminSecretNamespace: {{ .Values.namespace }}
  imageFeatures: layering
  imageFormat: "2"
  monitors: {{ .Values.storageclass.monitors }}
  pool: {{ .Values.storageclass.pool }}
  userId: {{ .Values.storageclass.id.user }}
  userSecretName: {{ .Values.secret.ceph.name }}
provisioner: {{ .Values.storageclass.provisioner }}
reclaimPolicy: {{ .Values.storageclass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageclass.volumeBindingMode }}
