kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    run: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  externalIPs:
  - 192.168.1.117
# 注意,此处IP必须在k8s集群中节点上已配置好.