apiVersion: v1
kind: Service
metadata:
  labels:
    service-name: demo-svc-nginx
  name: demo-svc-nginx
spec:
  clusterIP: 
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32080
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 32443
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
