apiVersion: v1
kind: Service
metadata:
  labels:
    service-name: demo-svc-nginx
  name: demo-svc-nginx
spec:
  clusterIP: 
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    application-real-name: demo-nginx-20180428133944447
    version-id: version-id-50000036
  sessionAffinity: None
#  sessionAffinity: ClientIP  
#  此配置项可保持基于客户端IP的方式进行负载
  type: ClusterIP
