apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-rbd
parameters:
  adminId: admin
  adminSecretName: ceph-admin-secret
  adminSecretNamespace: kube-system
  imageFeatures: layering
  imageFormat: "2"
  monitors: 192.168.1.114:6789
  pool: rbd
  userId: k8s
  userSecretName: ceph-secret
provisioner: ceph.com/rbd
reclaimPolicy: Delete
volumeBindingMode: Immediate
