apiVersion: v1
data:
  secret: QVFBczNoQmJYdXYvR3hBQXFSbG9LaDhEMkRiVVRMeGRhNUV2TFE9PQ==
kind: Secret
metadata:
  name: ceph-admin-secret
  namespace: kube-system
type: Opaque
---
apiVersion: v1
data:
  secret: QVFBQjZoQmJXMW82SkJBQUMzbG9CUnhvbUY2MVJ4V2pKSXR6eXc9PQ==
kind: Secret
metadata:
  name: ceph-secret
type: Opaque
