apiVersion: v1
kind: Secret
metadata:
  name: mysql-info-secret
type: Opaque
data:
  mysql-root-password: b25jZWFz
  mysql-password: emFiYml4
  mysql-user: emFiYml4
  mysql-database: emFiYml4
  mysql-root-host: JQ==
# root password onceas
# databases user : zabbix
# root-host : %

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-name: demo-svc-mysql
  name: demo-svc-mysql
spec:
  clusterIP: 
  externalTrafficPolicy: Cluster
  ports:
  - name: tcp
    nodePort: 31336
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: mysql-secret-demo
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    name: mysql-secret-demo
  name: mysql-57
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-secret-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: mysql-secret-demo
    spec:
      containers:
      - args:
        - mysqld
        command:
        - docker-entrypoint.sh
        env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-info-secret
              key: mysql-root-password
        - name: MYSQL_ROOT_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-info-secret
              key: mysql-root-host
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-info-secret
              key: mysql-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-info-secret
              key: mysql-user
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-info-secret
              key: mysql-database        
        image: registry.cn-hangzhou.aliyuncs.com/jihongrui/mysql:v5.7
        imagePullPolicy: IfNotPresent
        name: mysql-57
        ports:
        - containerPort: 3306
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: mysql-data
